### PR TITLE
chromium.inc: update DEPENDS

### PR DESCRIPTION
**Pull request by twoerner**
The gypi file for this recipe explicitly requests that xkbcommon be used,
therefore adding a dependency on it.

Signed-off-by: Trevor Woerner twoerner@gmail.com

### CODE REVIEW

**Comment by zoltan-ongithub** [comment]
Thanks for the patch. We already have this dependency for Wayland builds, set by CHROMIUM_WAYLAND_DEPENDS. Isn't libxkbcommon automatically pulled in by having x11 in DISTRO_FEATURES?

If we need this for x11 based builds as well, the patch should remove libxkbcommon from the CHROMIUM_WAYLAND_DEPENDS.

**Comment by twoerner** [comment]
Hi Zoltan, thanks for the feedback!

I see what you mean with the wayland builds. I stumbled upon this a while back, I was doing x11 builds and going through cycles of deleting sstate and tmp then just bitbaking chromium by itself. I'll do some more testing to confirm and get back to you either way.

**Comment by twoerner** [comment]
I've just completed a bunch of tests and here's what I found: I can't reproduce this error when building with the RPB (and swapping out its meta-browser for the LHG one), but if I do a build using the minimum layers required and nodistro, then this dependency issue shows up even when "x11" is in DISTRO_FEATURES. In all tests I'm only doing x11 builds (i.e. not wayland builds) and, starting from scratch, I'm only building the chromium target (i.e. not an image that includes chromium).

So it's up to you. If anyone is using this layer on their own they might see the problem. but even at that the chances are low since most will probably be building an image and xkbcommon will probably be built as part of the image. I just had a weird use-case.

**Comment by zoltan-ongithub** [comment]
We are not doing X11 based builds, but I'm happy to get that fixed. On the other hand, libxkbcommon needs to be than removed from CHROMIUM_WAYLAND_DEPENDS.

**Pull request closed without merging**
